### ISSUE TITLE
Could this be ported to Firefox..?

### ISSUE THREAD

**Issue by dwaal** [Dongw1126/Auto-Resume-Downloads#1]
I use both Chrome and Firefox. It would be nice to have this add-on also in Firefox. Any chance this is possible?

**Comment by Dongw1126** [comment]
I don't have any plans for the Firefox version yet, but I'll update it soon. Thank you.

**Comment by dwaal** [comment]
Thanks. By update it soon, it means you will port it to Firefox? Much appreciated. Great work :+1:

**Comment by Dongw1126** [comment]
Yeah, I'll try to make it available to Firefox.

**Comment by Dongw1126** [comment]
I tried to port this extension to Firefox Add-on.
But Firefox's "canResume" was far from Chrome.
Firefox API does not allow resume for an error-stopped download.
![image](https://user-images.githubusercontent.com/48395704/108633742-3e6c7880-74b9-11eb-93a5-0b7c861365ca.png)
So I think it will be difficult to port to Firefox. I'm sorry I couldn't help you.

**Comment by Dongw1126** [comment]
I tried to port this extension to Firefox Add-on.
But Firefox's "canResume" was far from Chrome.
Firefox API does not allow resume for an error-stopped download.
![image](https://user-images.githubusercontent.com/48395704/108633742-3e6c7880-74b9-11eb-93a5-0b7c861365ca.png)
So I think it will be difficult to port to Firefox now. I'm sorry I couldn't help you.

**Comment by dwaal** [comment]
Strange. You can press the "Retry" icon in the download manager...but I guess they didn't offer it in the API?

Aren't there many download managers in Firefox that offer resume? I was hoping for a minimal solution though.

**Comment by Dongw1126** [comment]
![image](https://user-images.githubusercontent.com/48395704/108634175-b5a30c00-74bb-11eb-9805-7e92ac26aa10.png)

Yes, I think it's weird, too. 
I can press retry button in the Download Manager, but I cannot call <code>browser.downloads.resume</code> in the API.

**Comment by dwaal** [comment]
This is a bug I think. I just looked and nobody filed it yet.

https://discourse.mozilla.org/t/webextension-retry-failed-download/60252/6
https://discourse.mozilla.org/t/browser-downloads-resume-is-not-the-same-as-retry/75057/3

**Comment by dwaal** [comment]
Did more digging.

Seems like it worked before. So it is in the API but it is broken. There is an old auto-resume Firefox plugin, but it seems broken.

Will you file a bug?

**Comment by Dongw1126** [comment]
Thank you for your effort. I will submit this issue to Mozilla. 
When the problem is solved, I will try to develop the Firefox version.
